name: github action Action
on:
  pull_request:
    types:
      - closed
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Specifies the checkout action
      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true  
      - name: Install bundle
        run: bundle install  # Specifies the custom command to run
      - name: Install fastlane
        run: gem install fastlane && gem install dotenv # Install Fastlane and install dotenv
      - name: Distribute to Firebase
        run: bundle exec fastlane distribute_app --env development
